name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_IMAGE_PREFIX: ghcr.io/${{ github.repository }}/bsc-node
      SNAPSHOT_EXTRACTOR_IMAGE_PREFIX: ghcr.io/${{ github.repository }}/snapshot_extractor

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch all tags
        run: |
          git fetch --tags
          echo "Listing all tags:"
          git tag --points-at HEAD

      - name: Format Git tags
        id: format_tags
        run: |
          tags=$(git tag --points-at HEAD)
          formatted_tags=""
          if [ -z "$tags" ]; then
            echo "No tags found at HEAD."
          else
            for tag in $tags; do
              formatted_tags+=",${{ env.IMAGE_PREFIX }}:$tag"
            done
            # Remove trailing space
            formatted_tags=$(echo $formatted_tags | xargs)
          fi

          # Print formatted tags to the environment
          echo "formatted_tags=$formatted_tags" >> $GITHUB_ENV


      - name: Build and push Node Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          tags: |
            ${{ env.NODE_IMAGE_PREFIX }}:latest
            ${{ env.formatted_tags }}

      - name: Build and push Extractor Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./snapshot_extractor
          push: true
          no-cache: true
          tags: |
            ${{ env.SNAPSHOT_EXTRACTOR_IMAGE_PREFIX }}:latest
            ${{ env.formatted_tags }}
      

      - name: Post build info
        run: echo "Docker images has been built and pushed"
